function [K] = ku0v0(x, y, xp, yp, hyp, ubar, vbar, ubarp, vbarp, dt, i)

logsigma = hyp(1);
logthetax = hyp(2);
logthetay = hyp(3);

a1 = hyp(4);
a2 = hyp(5);

logsigmap = hyp(6);
logthetaxp = hyp(7);
logthetayp = hyp(8);

n_x = size(x,1);
n_y = size(y,1);
n_xp = size(xp,1);
n_yp = size(yp,1);

x = repmat(x,1,n_xp);
y = repmat(y,1,n_yp);
xp = repmat(xp',n_x,1);
yp = repmat(yp',n_y,1);

ubar = repmat(ubar,1,n_xp);
vbar = repmat(vbar,1,n_yp);
ubarp = repmat(ubarp',n_x,1);
vbarp = repmat(vbarp',n_y,1);

switch i


case 0

K=(-1).*dt.^2.*exp(1).^(logsigmap+(-1).*logthetaxp+(-1).*logthetayp+(-1/2) ...
  .*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).* ...
  logthetayp).*(y+(-1).*yp).^2).*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^( ...
  logsigma+(-3).*logthetax+(-3).*logthetay+(-1/2).*exp(1).^((-1).* ...
  logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).* ...
  yp).^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+( ...
  -1).*dt.*exp(1).^(a2+logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).* ...
  exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).* ...
  logthetay).*(y+(-1).*yp).^2).*(2.*dt.*exp(1).^(4.*logthetax+2.* ...
  logthetay).*(x+(-1).*xp).*(a1.*exp(1).^logthetay.*vbarp+(-3).*exp(1) ...
  .^a2.*(y+(-1).*yp))+(-2).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .*(a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.* ...
  dt.*exp(1).^(2.*logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+( ...
  -3).*exp(1).^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.* ...
  logthetax+logthetay).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay)) ...
  +dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^( ...
  logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+( ...
  -1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1) ...
  .*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).* ...
  (y+(-1).*yp).^2).*(y+(-1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1) ...
  .^logthetax+(x+(-1).*xp).^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.* ...
  dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1) ...
  .*y+yp))))+exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  a1.*dt.*exp(1).^(logsigma+(-4).*logthetax+(-4).*logthetay+(-1/2).*exp(1) ...
  .^((-1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).* ...
  (y+(-1).*yp).^2).*(exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*(a1.* ...
  dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay) ...
  .*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay) ...
  .*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+ ...
  2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1) ...
  .^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1).*(x+(-1).*xp).*( ...
  (x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.* ...
  exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+( ...
  -1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.* ...
  logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+ ...
  exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^( ...
  logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+exp( ...
  1).^logthetax.*vbar.*(exp(1).^logthetay.*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1).*(y+(-1).*yp).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))));


case 1 % logsigma

K=exp(1).^(logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).*exp(1).^((-1) ...
  .*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1) ...
  .*yp).^2).*(exp(1).^(2.*(logthetax+logthetay)).*((x+(-1).*xp).*(exp(1) ...
  .^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+(-1).*dt.*exp(1).^a2.*(2.* ...
  dt.*exp(1).^(4.*logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*exp(1) ...
  .^logthetay.*vbarp+(-3).*exp(1).^a2.*(y+(-1).*yp))+(-2).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.*dt.*exp(1).^(2.* ...
  logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+(-3).*exp(1) ...
  .^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.*logthetax+logthetay) ...
  .*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*( ...
  3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+ ...
  (-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.* ...
  logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*(( ...
  -1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+( ...
  -1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+( ...
  -2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2).*(y+( ...
  -1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1).^logthetax+(x+(-1).*xp) ...
  .^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+ ...
  exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp).^2).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+a1.*dt.*exp(1) ...
  .^(logthetax+logthetay).*(exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*( ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1) ...
  .*(x+(-1).*xp).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+ ...
  2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1) ...
  .^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  exp(1).^logthetax.*vbar.*(exp(1).^logthetay.*((x+(-1).*xp).*(exp(1).^( ...
  2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1).*(y+(-1).*yp).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))));


case 2 % logthetax

K=exp(1).^(logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).*exp(1).^((-1) ...
  .*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1) ...
  .*yp).^2).*(exp(1).^(2.*(logthetax+logthetay)).*((-3)+(1/2).*exp(1).^(( ...
  -1).*logthetax).*(x+(-1).*xp).^2).*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*(logthetax+ ...
  logthetay)).*((x+(-1).*xp).*(2.*exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^(a2+logthetax).*(3.*exp(1).^(2.*logthetay)+6.*exp(1).^( ...
  logthetax+logthetay)+(-2).*exp(1).^logthetax.*(y+(-1).*yp).^2)).*(y+(-1) ...
  .*yp)+a1.*dt.*exp(1).^(2.*logthetax+logthetay).*(vbarp.*(x+(-1).*xp).*( ...
  y+(-1).*yp).^2+exp(1).^logthetay.*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+ ...
  yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*( ...
  y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ ...
  ubarp.*((-1).*y+yp))))+(-1).*dt.*exp(1).^a2.*((-5)+(1/2).*exp(1).^((-1) ...
  .*logthetax).*(x+(-1).*xp).^2).*(2.*dt.*exp(1).^(4.*logthetax+2.* ...
  logthetay).*(x+(-1).*xp).*(a1.*exp(1).^logthetay.*vbarp+(-3).*exp(1) ...
  .^a2.*(y+(-1).*yp))+(-2).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .*(a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.* ...
  dt.*exp(1).^(2.*logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+( ...
  -3).*exp(1).^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.* ...
  logthetax+logthetay).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay)) ...
  +dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^( ...
  logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+( ...
  -1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1) ...
  .*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).* ...
  (y+(-1).*yp).^2).*(y+(-1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1) ...
  .^logthetax+(x+(-1).*xp).^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.* ...
  dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1) ...
  .*y+yp))))+exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+( ...
  -1).*dt.*exp(1).^a2.*(8.*dt.*exp(1).^(4.*logthetax+2.*logthetay).*(x+( ...
  -1).*xp).*(a1.*exp(1).^logthetay.*vbarp+(-3).*exp(1).^a2.*(y+(-1).*yp))+ ...
  (-2).*exp(1).^(2.*(logthetax+logthetay)).*(x+(-1).*xp).*((-2).*a1.*dt.* ...
  exp(1).^logthetay.*(exp(1).^(logthetax+logthetay).*vbarp+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+(-1).*exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(2.*exp(1).^(logthetax+2.*logthetay)+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetay)+6.*exp(1).^(logthetax+logthetay)+(-2).* ...
  exp(1).^logthetax.*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-2).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.*a1.*dt.*exp(1).^(3.* ...
  logthetax+4.*logthetay).*ubarp.*(y+(-1).*yp)+4.*dt.*exp(1).^(2.* ...
  logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+(-3).*exp(1) ...
  .^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(3.*logthetax+logthetay) ...
  .*((x+(-1).*xp).*(2.*exp(1).^(logthetax+2.*logthetay)+3.*dt.*exp(1) ...
  .^a2.*(exp(1).^(2.*logthetay)+2.*exp(1).^(logthetax+logthetay)+(-2).* ...
  exp(1).^logthetax.*(y+(-1).*yp).^2))+(-1).*a1.*dt.*exp(1).^logthetay.*( ...
  2.*exp(1).^(logthetax+logthetay).*ubarp+(-1).*exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2+(-4).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp))).*(y+(-1).*yp)+(-4).*exp(1).^(2.*logthetax+logthetay).*((x+(-1).* ...
  xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^( ...
  2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1) ...
  .^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1) ...
  .*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^( ...
  logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+ ...
  2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp( ...
  1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2).*(y+(-1).*yp)+(-1) ...
  .*exp(1).^(logthetax+2.*logthetay).*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+2.*exp(1).^(2.*logthetax).*(( ...
  -1).*exp(1).^logthetay+(y+(-1).*yp).^2).*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*logthetay).*((-1) ...
  .*exp(1).^logthetax+(x+(-1).*xp).^2).*((x+(-1).*xp).*(2.*exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^(a2+logthetax).*(3.*exp(1).^(2.* ...
  logthetay)+6.*exp(1).^(logthetax+logthetay)+(-2).*exp(1).^logthetax.*(y+ ...
  (-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(2.*logthetax+logthetay).*( ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^logthetay.*(vbarp.*((-1).* ...
  x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp( ...
  1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*logthetax).*((-1) ...
  .*exp(1).^logthetay+(y+(-1).*yp).^2).*((x+(-1).*xp).*(2.*exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^(a2+logthetax).*(3.*exp(1).^(2.* ...
  logthetay)+6.*exp(1).^(logthetax+logthetay)+(-2).*exp(1).^logthetax.*(y+ ...
  (-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(2.*logthetax+logthetay).*( ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^logthetay.*(vbarp.*((-1).* ...
  x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp( ...
  1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-4)+(1/2).*exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2).*( ...
  exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*(a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.* ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1).*(x+(-1).*xp).*((x+ ...
  (-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp( ...
  1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+exp(1) ...
  .^logthetax.*vbar.*(exp(1).^logthetay.*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1).*(y+(-1).*yp).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))))+a1.*dt.*exp(1) ...
  .^(logthetax+logthetay).*(exp(1).^logthetax.*vbar.*(exp(1).^logthetay.*( ...
  (x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.* ...
  exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+( ...
  -1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.* ...
  logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*(( ...
  -1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+( ...
  -1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+( ...
  -2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1) ...
  .*(y+(-1).*yp).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+ ...
  2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1) ...
  .^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  exp(1).^logthetay.*ubar.*(exp(1).^(2.*logthetax).*((-2).*a1.*dt.*exp(1) ...
  .^logthetay.*(exp(1).^(logthetax+logthetay).*vbarp+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+(-1).*exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(2.*exp(1).^(logthetax+2.*logthetay)+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetay)+6.*exp(1).^(logthetax+logthetay)+(-2).* ...
  exp(1).^logthetax.*(y+(-1).*yp).^2)).*(y+(-1).*yp))+exp(1).^logthetax.*( ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1) ...
  .*(x+(-1).*xp).*((x+(-1).*xp).*(2.*exp(1).^(2.*(logthetax+logthetay))+ ...
  dt.*exp(1).^(a2+logthetax).*(3.*exp(1).^(2.*logthetay)+6.*exp(1).^( ...
  logthetax+logthetay)+(-2).*exp(1).^logthetax.*(y+(-1).*yp).^2)).*(y+(-1) ...
  .*yp)+a1.*dt.*exp(1).^(2.*logthetax+logthetay).*(vbarp.*(x+(-1).*xp).*( ...
  y+(-1).*yp).^2+exp(1).^logthetay.*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+ ...
  yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*( ...
  y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ ...
  ubarp.*((-1).*y+yp)))))+exp(1).^logthetax.*vbar.*(exp(1).^(logthetax+ ...
  logthetay).*((x+(-1).*xp).*(2.*exp(1).^(logthetax+2.*logthetay)+3.*dt.* ...
  exp(1).^a2.*(exp(1).^(2.*logthetay)+2.*exp(1).^(logthetax+logthetay)+( ...
  -2).*exp(1).^logthetax.*(y+(-1).*yp).^2))+(-1).*a1.*dt.*exp(1) ...
  .^logthetay.*(2.*exp(1).^(logthetax+logthetay).*ubarp+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+(-4).*exp(1).^logthetax.*vbarp.*(x+( ...
  -1).*xp).*(y+(-1).*yp)))+(-1).*(y+(-1).*yp).*((x+(-1).*xp).*(2.*exp(1) ...
  .^(2.*(logthetax+logthetay))+dt.*exp(1).^(a2+logthetax).*(3.*exp(1).^( ...
  2.*logthetay)+6.*exp(1).^(logthetax+logthetay)+(-2).*exp(1).^logthetax.* ...
  (y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(2.*logthetax+logthetay) ...
  .*(vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^logthetay.*(vbarp.*((-1) ...
  .*x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))));


case 3 % logthetay

K=exp(1).^(logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).*exp(1).^((-1) ...
  .*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1) ...
  .*yp).^2).*(exp(1).^(2.*(logthetax+logthetay)).*((-3)+(1/2).*exp(1).^(( ...
  -1).*logthetay).*(y+(-1).*yp).^2).*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*(logthetax+ ...
  logthetay)).*((2.*exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^(a2+ ...
  logthetay).*(3.*exp(1).^(2.*logthetax)+6.*exp(1).^(logthetax+logthetay)+ ...
  (-2).*exp(1).^logthetay.*(x+(-1).*xp).^2)).*(x+(-1).*xp).*(y+(-1).*yp)+ ...
  a1.*dt.*exp(1).^(logthetax+2.*logthetay).*(ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))+ ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+( ...
  -1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*( ...
  (-1).*y+yp))))+(-1).*dt.*exp(1).^a2.*((-5)+(1/2).*exp(1).^((-1).* ...
  logthetay).*(y+(-1).*yp).^2).*(2.*dt.*exp(1).^(4.*logthetax+2.* ...
  logthetay).*(x+(-1).*xp).*(a1.*exp(1).^logthetay.*vbarp+(-3).*exp(1) ...
  .^a2.*(y+(-1).*yp))+(-2).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .*(a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.* ...
  dt.*exp(1).^(2.*logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+( ...
  -3).*exp(1).^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.* ...
  logthetax+logthetay).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay)) ...
  +dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^( ...
  logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+( ...
  -1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1) ...
  .*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).* ...
  (y+(-1).*yp).^2).*(y+(-1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1) ...
  .^logthetax+(x+(-1).*xp).^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.* ...
  dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1) ...
  .*y+yp))))+exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+( ...
  -1).*dt.*exp(1).^a2.*(2.*a1.*dt.*exp(1).^(4.*logthetax+3.*logthetay).* ...
  vbarp.*(x+(-1).*xp)+4.*dt.*exp(1).^(4.*logthetax+2.*logthetay).*(x+(-1) ...
  .*xp).*(a1.*exp(1).^logthetay.*vbarp+(-3).*exp(1).^a2.*(y+(-1).*yp))+( ...
  -2).*exp(1).^(logthetax+3.*logthetay).*(x+(-1).*xp).*((-1).*a1.*dt.*exp( ...
  1).^logthetax.*(2.*exp(1).^(logthetax+logthetay).*vbarp+(-4).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+(-1).*exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(2.*exp(1).^(2.*logthetax+logthetay)+3.*dt.*exp( ...
  1).^a2.*(exp(1).^(2.*logthetax)+2.*exp(1).^(logthetax+logthetay)+(-2).* ...
  exp(1).^logthetay.*(x+(-1).*xp).^2)).*(y+(-1).*yp))+(-4).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+8.*dt.*exp(1).^(2.* ...
  logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+(-3).*exp(1) ...
  .^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.*(logthetax+ ...
  logthetay)).*((2.*exp(1).^(2.*logthetax+logthetay)+dt.*exp(1).^a2.*(3.* ...
  exp(1).^(2.*logthetax)+6.*exp(1).^(logthetax+logthetay)+(-2).*exp(1) ...
  .^logthetay.*(x+(-1).*xp).^2)).*(x+(-1).*xp)+(-2).*a1.*dt.*exp(1) ...
  .^logthetax.*(exp(1).^(logthetax+logthetay).*ubarp+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+(-1).*exp(1).^logthetax.*vbarp.*(x+( ...
  -1).*xp).*(y+(-1).*yp))).*(y+(-1).*yp)+(-2).*exp(1).^(2.*logthetax+ ...
  logthetay).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp( ...
  1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).* ...
  ((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*( ...
  x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+ ...
  (-2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2).*(y+ ...
  (-1).*yp)+(-1).*exp(1).^(2.*logthetax+logthetay).*((x+(-1).*xp).*(exp(1) ...
  .^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+2.*exp(1).^(2.*logthetay).*(( ...
  -1).*exp(1).^logthetax+(x+(-1).*xp).^2).*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*logthetay).*((-1) ...
  .*exp(1).^logthetax+(x+(-1).*xp).^2).*((2.*exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^(a2+logthetay).*(3.*exp(1).^(2.*logthetax)+6.* ...
  exp(1).^(logthetax+logthetay)+(-2).*exp(1).^logthetay.*(x+(-1).*xp).^2)) ...
  .*(x+(-1).*xp).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+2.*logthetay).*( ...
  ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*(vbarp.*((-1).* ...
  x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp( ...
  1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+exp(1).^(2.*logthetax).*((-1) ...
  .*exp(1).^logthetay+(y+(-1).*yp).^2).*((2.*exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^(a2+logthetay).*(3.*exp(1).^(2.*logthetax)+6.* ...
  exp(1).^(logthetax+logthetay)+(-2).*exp(1).^logthetay.*(x+(-1).*xp).^2)) ...
  .*(x+(-1).*xp).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+2.*logthetay).*( ...
  ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*(vbarp.*((-1).* ...
  x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1).^(logthetax+logthetay).*(exp( ...
  1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*( ...
  vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-4)+(1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*( ...
  exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*(a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.* ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1).*(x+(-1).*xp).*((x+ ...
  (-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp( ...
  1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+exp(1) ...
  .^logthetax.*vbar.*(exp(1).^logthetay.*((x+(-1).*xp).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1).*(y+(-1).*yp).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))))+a1.*dt.*exp(1) ...
  .^(logthetax+logthetay).*(exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*( ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1) ...
  .*(x+(-1).*xp).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+ ...
  2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1) ...
  .^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  exp(1).^logthetay.*ubar.*(exp(1).^(logthetax+logthetay).*((-1).*a1.*dt.* ...
  exp(1).^logthetax.*(2.*exp(1).^(logthetax+logthetay).*vbarp+(-4).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+(-1).*exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(2.*exp(1).^(2.*logthetax+logthetay)+3.*dt.*exp( ...
  1).^a2.*(exp(1).^(2.*logthetax)+2.*exp(1).^(logthetax+logthetay)+(-2).* ...
  exp(1).^logthetay.*(x+(-1).*xp).^2)).*(y+(-1).*yp))+(-1).*(x+(-1).*xp).* ...
  ((2.*exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^(a2+logthetay).*(3.* ...
  exp(1).^(2.*logthetax)+6.*exp(1).^(logthetax+logthetay)+(-2).*exp(1) ...
  .^logthetay.*(x+(-1).*xp).^2)).*(x+(-1).*xp).*(y+(-1).*yp)+a1.*dt.*exp( ...
  1).^(logthetax+2.*logthetay).*(ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp( ...
  1).^logthetax.*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))+a1.*dt.*exp(1) ...
  .^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  exp(1).^logthetax.*vbar.*(exp(1).^(2.*logthetay).*((2.*exp(1).^(2.* ...
  logthetax+logthetay)+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax)+6.*exp( ...
  1).^(logthetax+logthetay)+(-2).*exp(1).^logthetay.*(x+(-1).*xp).^2)).*( ...
  x+(-1).*xp)+(-2).*a1.*dt.*exp(1).^logthetax.*(exp(1).^(logthetax+ ...
  logthetay).*ubarp+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+(-1).* ...
  exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp)))+exp(1) ...
  .^logthetay.*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp( ...
  1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).* ...
  ((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*( ...
  x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+ ...
  (-2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1) ...
  .*(y+(-1).*yp).*((2.*exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^(a2+ ...
  logthetay).*(3.*exp(1).^(2.*logthetax)+6.*exp(1).^(logthetax+logthetay)+ ...
  (-2).*exp(1).^logthetay.*(x+(-1).*xp).^2)).*(x+(-1).*xp).*(y+(-1).*yp)+ ...
  a1.*dt.*exp(1).^(logthetax+2.*logthetay).*(ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))+ ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+( ...
  -1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*( ...
  (-1).*y+yp)))))));


case 4 % a1

K=dt.*exp(1).^(logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).*exp(1).^(( ...
  -1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+( ...
  -1).*yp).^2).*(exp(1).^(3.*(logthetax+logthetay)).*(exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).* ...
  xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp) ...
  +ubarp.*((-1).*y+yp)))+(-1).*dt.*exp(1).^(a2+logthetax+logthetay).*(2.* ...
  exp(1).^(3.*logthetax+2.*logthetay).*vbarp.*(x+(-1).*xp)+(-2).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+2.*exp(1).^(2.*logthetax+ ...
  3.*logthetay).*ubarp.*(y+(-1).*yp)+(-2).*exp(1).^(2.*logthetax+ ...
  logthetay).*((-1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1) ...
  .*xp).*(y+(-1).*yp)).*(y+(-1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1) ...
  .^logthetax+(x+(-1).*xp).^2).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp) ...
  .^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+ ...
  yp)))+exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp).^2) ...
  .*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+a1.*dt.*exp(1) ...
  .^(2.*(logthetax+logthetay)).*(exp(1).^logthetay.*ubar.*(exp(1) ...
  .^logthetax.*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-1).*(x+(-1).*xp).*(exp(1).^logthetay.*ubarp.*( ...
  x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+ ...
  (-1).*yp).^2+exp(1).^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.* ...
  ((-1).*y+yp))))+exp(1).^logthetax.*vbar.*(exp(1).^logthetay.*((-1).*exp( ...
  1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-1).*(y+( ...
  -1).*yp).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp( ...
  1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubar.*(exp(1).^logthetax.*( ...
  a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*vbarp+2.*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+(-1) ...
  .*(x+(-1).*xp).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.* ...
  exp(1).^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+ ...
  2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1) ...
  .^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))+ ...
  exp(1).^logthetax.*vbar.*(exp(1).^logthetay.*((x+(-1).*xp).*(exp(1).^( ...
  2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*((-1).*exp(1).^(logthetax+ ...
  logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+2.*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2)+(-1).*(y+(-1).*yp).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp)))))));


case 5 % a2

K=dt.*exp(1).^(logsigma+(-5).*logthetax+(-5).*logthetay+(-1/2).*exp(1).^(( ...
  -1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+( ...
  -1).*yp).^2).*(a1.*dt.*exp(1).^(a2+logthetax+logthetay).*(exp(1) ...
  .^logthetax.*vbar.*(x+(-1).*xp).*(exp(1).^logthetay.*(3.*exp(1).^(2.* ...
  logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+(-3).*exp(1).^(2.*logthetax).*(y+(-1).* ...
  yp).^2)+(-1).*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^( ...
  logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+( ...
  -1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2).*(y+(-1).*yp).^2)+exp(1) ...
  .^logthetay.*ubar.*(exp(1).^logthetax.*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-3).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2)+(-1).*(x+(-1).*xp).^2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp( ...
  1).^(logthetax+2.*logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp) ...
  .^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+exp( ...
  1).^(a2+2.*(logthetax+logthetay)).*(x+(-1).*xp).*(3.*exp(1).^(2.* ...
  logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1).* ...
  yp).^2).*(y+(-1).*yp)+(-1).*dt.*exp(1).^(2.*a2).*(x+(-1).*xp).*((-18).* ...
  exp(1).^(3.*(logthetax+logthetay))+(-15).*exp(1).^(4.*logthetax+2.* ...
  logthetay)+(-15).*exp(1).^(2.*logthetax+4.*logthetay)+6.*exp(1).^(2.* ...
  logthetax+3.*logthetay).*(x+(-1).*xp).^2+10.*exp(1).^(logthetax+4.* ...
  logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(4.*logthetay).*(x+(-1).*xp) ...
  .^4+10.*exp(1).^(4.*logthetax+logthetay).*(y+(-1).*yp).^2+6.*exp(1).^( ...
  3.*logthetax+2.*logthetay).*(y+(-1).*yp).^2+(-2).*exp(1).^(2.*( ...
  logthetax+logthetay)).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2+(-1).*exp(1).^( ...
  4.*logthetax).*(y+(-1).*yp).^4).*(y+(-1).*yp)+(-1).*exp(1).^a2.*(2.*dt.* ...
  exp(1).^(4.*logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*exp(1) ...
  .^logthetay.*vbarp+(-3).*exp(1).^a2.*(y+(-1).*yp))+(-2).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).*(a1.*dt.*exp(1).^(logthetax+ ...
  logthetay).*((-1).*exp(1).^(logthetax+logthetay).*vbarp+2.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(a2+2.*logthetay).*(x+(-1).* ...
  xp).^2.*(y+(-1).*yp)+(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp))+2.*dt.*exp(1).^(2.* ...
  logthetax+4.*logthetay).*(a1.*exp(1).^logthetax.*ubarp+(-3).*exp(1) ...
  .^a2.*(x+(-1).*xp)).*(y+(-1).*yp)+(-2).*exp(1).^(2.*logthetax+logthetay) ...
  .*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*( ...
  3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+ ...
  (-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.* ...
  logthetax).*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(logthetax+logthetay).*(( ...
  -1).*exp(1).^(logthetax+logthetay).*ubarp+exp(1).^logthetay.*ubarp.*(x+( ...
  -1).*xp).^2+2.*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+( ...
  -2).*dt.*exp(1).^(a2+2.*logthetax).*(x+(-1).*xp).*(y+(-1).*yp).^2).*(y+( ...
  -1).*yp)+exp(1).^(2.*logthetay).*((-1).*exp(1).^logthetax+(x+(-1).*xp) ...
  .^2).*((x+(-1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1) ...
  .^a2.*(3.*exp(1).^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.* ...
  logthetay)+(-1).*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^( ...
  2.*logthetax).*(y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^( ...
  logthetax+logthetay).*(exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+( ...
  -1).*yp)+exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1) ...
  .^(logthetax+logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))+ ...
  exp(1).^(2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp).^2).*((x+( ...
  -1).*xp).*(exp(1).^(2.*(logthetax+logthetay))+dt.*exp(1).^a2.*(3.*exp(1) ...
  .^(2.*logthetax+logthetay)+3.*exp(1).^(logthetax+2.*logthetay)+(-1).* ...
  exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*( ...
  y+(-1).*yp).^2)).*(y+(-1).*yp)+a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)+exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp).^2+exp(1).^(logthetax+ ...
  logthetay).*(vbarp.*((-1).*x+xp)+ubarp.*((-1).*y+yp))))));


case 6 % logsigmap

K=(-1).*dt.^2.*exp(1).^(logsigmap+(-1).*logthetaxp+(-1).*logthetayp+(-1/2) ...
  .*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).* ...
  logthetayp).*(y+(-1).*yp).^2).*(x+(-1).*xp).*(y+(-1).*yp);


case 7 % logthetaxp

K=(1/2).*dt.^2.*exp(1).^(logsigmap+(-2).*logthetaxp+(-1).*logthetayp+( ...
  -1/2).*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1) ...
  .*logthetayp).*(y+(-1).*yp).^2).*(2.*exp(1).^logthetaxp+(-1).*(x+(-1).* ...
  xp).^2).*(x+(-1).*xp).*(y+(-1).*yp);


case 8 % logthetayp

K=(1/2).*dt.^2.*exp(1).^(logsigmap+(-1).*logthetaxp+(-2).*logthetayp+( ...
  -1/2).*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1) ...
  .*logthetayp).*(y+(-1).*yp).^2).*(x+(-1).*xp).*(2.*exp(1).^logthetayp+( ...
  -1).*(y+(-1).*yp).^2).*(y+(-1).*yp);


otherwise
        
        K = zeros(n_x, n_xp);
end

end
