function [K] = kv0v0(x, y, xp, yp, hyp, ubar, vbar, ubarp, vbarp, dt, i)

logsigma = hyp(1);
logthetax = hyp(2);
logthetay = hyp(3);

a1 = hyp(4);
a2 = hyp(5);

logsigmap = hyp(6);
logthetaxp = hyp(7);
logthetayp = hyp(8);

n_x = size(x,1);
n_y = size(y,1);
n_xp = size(xp,1);
n_yp = size(yp,1);

x = repmat(x,1,n_xp);
y = repmat(y,1,n_yp);
xp = repmat(xp',n_x,1);
yp = repmat(yp',n_y,1);

ubar = repmat(ubar,1,n_xp);
vbar = repmat(vbar,1,n_yp);
ubarp = repmat(ubarp',n_x,1);
vbarp = repmat(vbarp',n_y,1);

switch i


case 0

K=a1.*dt.*exp(1).^(logsigma+(-5).*logthetax+(-1/2).*exp(1).^((-1).* ...
  logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).* ...
  yp).^2).*(ubar.*(exp(1).^logthetax.*((-2).*exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.* ...
  exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(2.* ...
  logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)) ...
  +(-1).*(x+(-1).*xp).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*( ...
  x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1) ...
  .^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)))+exp( ...
  1).^(logthetax+(-2).*logthetay).*vbar.*(a1.*dt.*exp(1).^(2.*logthetax+ ...
  logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+(-2).*dt.* ...
  exp(1).^(a2+2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*( ...
  y+(-1).*yp)+(-1).*exp(1).^logthetay.*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp)))+exp(1).^(logsigma+(-4).* ...
  logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2+(-1/2).* ...
  exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(exp(1).^(2.*logthetax).*( ...
  exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1) ...
  .*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+( ...
  -1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2))+(-1).*dt.*exp(1).^(a2+logsigma+(-6).* ...
  logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2+(-1/2).* ...
  exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*((-2).*dt.*exp(1).^(a2+4.* ...
  logthetax+(-2).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+( ...
  -2).*exp(1).^logthetax.*(x+(-1).*xp).*((-2).*exp(1).^(2.*logthetax).*(x+ ...
  (-1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.* ...
  exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(2.* ...
  logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)) ...
  +(-2).*exp(1).^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*(exp(1).^(a2+2.*logthetax+logthetay)+6.*exp(1).^(a2+ ...
  logthetax+2.*logthetay)+3.*a1.*exp(1).^(logthetax+2.*logthetay).*ubarp.* ...
  (x+(-1).*xp)+(-6).*exp(1).^(a2+2.*logthetay).*(x+(-1).*xp).^2+a1.*exp(1) ...
  .^(2.*logthetax+logthetay).*vbarp.*(y+(-1).*yp)+(-1).*exp(1).^(a2+2.* ...
  logthetax).*(y+(-1).*yp).^2))+((-1).*exp(1).^logthetax+(x+(-1).*xp).^2) ...
  .*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+ ...
  a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+exp(1) ...
  .^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2)+(-2).*dt.*exp(1).^(4.*logthetax+(-3).*logthetay).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2).*(a1.*exp(1).^logthetay.*vbarp+(-2).* ...
  exp(1).^a2.*(y+(-1).*yp)).*(y+(-1).*yp))+dt.^2.*exp(1).^(logsigmap+(-2) ...
  .*logthetayp+(-1/2).*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2) ...
  .*exp(1).^((-1).*logthetayp).*(y+(-1).*yp).^2).*(exp(1).^logthetayp+(-1) ...
  .*(y+(-1).*yp).^2);


case 1 % logsigma

K=exp(1).^(logsigma+(-6).*logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+ ...
  (-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(a1.* ...
  dt.*exp(1).^logthetax.*(ubar.*(exp(1).^logthetax.*((-2).*exp(1).^(2.* ...
  logthetax).*(x+(-1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*( ...
  3.*exp(1).^(logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp))+2.*dt.*exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^( ...
  2.*logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1) ...
  .^(2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+(-1).*(x+(-1).*xp).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+( ...
  -1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.* ...
  exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+( ...
  -1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+ ...
  dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay)) ...
  +exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay) ...
  .*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax) ...
  .*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp) ...
  .^2)))+exp(1).^(logthetax+(-2).*logthetay).*vbar.*(a1.*dt.*exp(1).^(2.* ...
  logthetax+logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+( ...
  -2).*dt.*exp(1).^(a2+2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).* ...
  xp).^2).*(y+(-1).*yp)+(-1).*exp(1).^logthetay.*(exp(1).^(2.*logthetax).* ...
  (exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+( ...
  -1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+ ...
  (-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp)))+exp(1).^(2.*logthetax).*( ...
  exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.* ...
  dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+(-1).* ...
  dt.*exp(1).^a2.*((-2).*dt.*exp(1).^(a2+4.*logthetax+(-2).*logthetay).*( ...
  exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+(-2).*exp(1).^logthetax.*(x+( ...
  -1).*xp).*((-2).*exp(1).^(2.*logthetax).*(x+(-1).*xp)+a1.*dt.*exp(1).^( ...
  logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp+( ...
  -3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+(-2).*exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.*exp(1).^(a2+(-2).*logthetay).* ...
  (x+(-1).*xp).*((-1).*exp(1).^(2.*logthetax+logthetay)+(-6).*exp(1).^( ...
  logthetax+2.*logthetay)+2.*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+exp( ...
  1).^(2.*logthetax).*(y+(-1).*yp).^2))+(-2).*exp(1).^(2.*logthetax+(-2).* ...
  logthetay).*(exp(1).^(2.*(logthetax+logthetay))+dt.*(exp(1).^(a2+2.* ...
  logthetax+logthetay)+6.*exp(1).^(a2+logthetax+2.*logthetay)+3.*a1.*exp( ...
  1).^(logthetax+2.*logthetay).*ubarp.*(x+(-1).*xp)+(-6).*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2+a1.*exp(1).^(2.*logthetax+logthetay).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^(a2+2.*logthetax).*(y+(-1).*yp).^2))+( ...
  (-1).*exp(1).^logthetax+(x+(-1).*xp).^2).*(exp(1).^(2.*logthetax).*(exp( ...
  1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2))+exp(1).^(2.*logthetax+(-2).*logthetay).*( ...
  exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.* ...
  dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)).*((-1) ...
  .*exp(1).^logthetay+(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(4.*logthetax+( ...
  -3).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*(a1.*exp(1) ...
  .^logthetay.*vbarp+(-2).*exp(1).^a2.*(y+(-1).*yp)).*(y+(-1).*yp)));


case 2 % logthetax

K=exp(1).^(logsigma+(-6).*logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+ ...
  (-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(a1.* ...
  dt.*exp(1).^logthetax.*((-5)+(1/2).*exp(1).^((-1).*logthetax).*(x+(-1).* ...
  xp).^2).*(ubar.*(exp(1).^logthetax.*((-2).*exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.* ...
  exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(2.* ...
  logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)) ...
  +(-1).*(x+(-1).*xp).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*( ...
  x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1) ...
  .^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)))+exp( ...
  1).^(logthetax+(-2).*logthetay).*vbar.*(a1.*dt.*exp(1).^(2.*logthetax+ ...
  logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+(-2).*dt.* ...
  exp(1).^(a2+2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*( ...
  y+(-1).*yp)+(-1).*exp(1).^logthetay.*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp)))+exp(1).^(3.*logthetax).*( ...
  exp(1).^(2.*logthetax)+2.*exp(1).^logthetax.*(exp(1).^logthetax+(-1).*( ...
  x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp)+2.*exp(1).^logthetax.*vbarp.*(y+(-1).* ...
  yp)+(-1).*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+a1.*dt.*exp(1).^((-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*logthetax+ ...
  logthetay)+6.*exp(1).^(logthetax+2.*logthetay)+(-6).*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+(-2).*exp(1).^(logthetax+logthetay).*(x+(-1) ...
  .*xp).^2+(-3).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2+2.*exp(1) ...
  .^logthetax.*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+exp(1).^(2.*logthetax).* ...
  ((-4)+(1/2).*exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2).*(exp(1).^(2.* ...
  logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^( ...
  logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*( ...
  x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.* ...
  logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1) ...
  .*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^( ...
  2.*(logthetax+logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1) ...
  .^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2))+a1.*dt.*exp(1).^(2.*logthetax+(-3).* ...
  logthetay).*(exp(1).^(logthetax+2.*logthetay).*((-9).*exp(1).^( ...
  logthetax+logthetay).*ubar.*(x+(-1).*xp)+2.*exp(1).^logthetay.*ubar.*(x+ ...
  (-1).*xp).^3+(-4).*exp(1).^(2.*logthetax).*vbar.*(y+(-1).*yp)+3.*exp(1) ...
  .^logthetax.*vbar.*(x+(-1).*xp).^2.*(y+(-1).*yp))+a1.*dt.*exp(1) ...
  .^logthetay.*(9.*exp(1).^(2.*(logthetax+logthetay)).*ubar.*ubarp+4.*exp( ...
  1).^(3.*logthetax+logthetay).*vbar.*vbarp+(-12).*exp(1).^(logthetax+2.* ...
  logthetay).*ubar.*ubarp.*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*ubar.* ...
  ubarp.*(x+(-1).*xp).^4+(-3).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).*(vbar.*(vbarp.*(x+(-1).*xp)+3.*ubarp.*(y+(-1).*yp))+3.*ubar.* ...
  vbarp.*(y+(-1).*yp))+2.*exp(1).^(logthetax+logthetay).*(ubarp.*vbar+ ...
  ubar.*vbarp).*(x+(-1).*xp).^3.*(y+(-1).*yp)+(-4).*exp(1).^(3.*logthetax) ...
  .*vbar.*vbarp.*(y+(-1).*yp).^2+3.*exp(1).^(2.*logthetax).*vbar.*vbarp.*( ...
  x+(-1).*xp).^2.*(y+(-1).*yp).^2)+dt.*exp(1).^a2.*((-30).*exp(1).^( ...
  logthetax+3.*logthetay).*ubar.*(x+(-1).*xp)+10.*exp(1).^(3.*logthetay).* ...
  ubar.*(x+(-1).*xp).^3+(-9).*exp(1).^(2.*(logthetax+logthetay)).*(ubar.*( ...
  x+(-1).*xp)+vbar.*(y+(-1).*yp))+2.*exp(1).^(logthetax+2.*logthetay).*(x+ ...
  (-1).*xp).^2.*(ubar.*(x+(-1).*xp)+6.*vbar.*(y+(-1).*yp))+(-12).*exp(1) ...
  .^(3.*logthetax+logthetay).*vbar.*(y+(-1).*yp)+(-1).*exp(1).^(2.* ...
  logthetay).*vbar.*(x+(-1).*xp).^4.*(y+(-1).*yp)+9.*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).*(vbar.*(x+(-1).*xp)+ubar.*(y+(-1).* ...
  yp)).*(y+(-1).*yp)+(-2).*exp(1).^(logthetax+logthetay).*ubar.*(x+(-1).* ...
  xp).^3.*(y+(-1).*yp).^2+4.*exp(1).^(3.*logthetax).*vbar.*(y+(-1).*yp) ...
  .^3+(-3).*exp(1).^(2.*logthetax).*vbar.*(x+(-1).*xp).^2.*(y+(-1).*yp) ...
  .^3))+dt.*exp(1).^(a2+logthetax+(-4).*logthetay).*(exp(1).^(logthetax+ ...
  2.*logthetay).*(12.*exp(1).^(2.*(logthetax+logthetay))+5.*exp(1).^(3.* ...
  logthetax+logthetay)+(-4).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-18).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+2.*exp( ...
  1).^(2.*logthetay).*(x+(-1).*xp).^4+(-5).*exp(1).^(3.*logthetax).*(y+( ...
  -1).*yp).^2+4.*exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2) ...
  +dt.*(15.*exp(1).^(a2+4.*logthetax+2.*logthetay)+45.*exp(1).^(a2+2.* ...
  logthetax+4.*logthetay)+24.*exp(1).^(a2+3.*(logthetax+logthetay))+45.* ...
  a1.*exp(1).^(2.*logthetax+4.*logthetay).*ubarp.*(x+(-1).*xp)+(-36).*exp( ...
  1).^(a2+2.*logthetax+3.*logthetay).*(x+(-1).*xp).^2+(-90).*exp(1).^(a2+ ...
  logthetax+4.*logthetay).*(x+(-1).*xp).^2+(-20).*a1.*exp(1).^(logthetax+ ...
  4.*logthetay).*ubarp.*(x+(-1).*xp).^3+4.*exp(1).^(a2+logthetax+3.* ...
  logthetay).*(x+(-1).*xp).^4+15.*exp(1).^(a2+4.*logthetay).*(x+(-1).*xp) ...
  .^4+a1.*exp(1).^(4.*logthetay).*ubarp.*(x+(-1).*xp).^5+12.*a1.*exp(1).^( ...
  3.*(logthetax+logthetay)).*(ubarp.*(x+(-1).*xp)+vbarp.*(y+(-1).*yp))+( ...
  -3).*a1.*exp(1).^(2.*logthetax+3.*logthetay).*(x+(-1).*xp).^2.*(ubarp.*( ...
  x+(-1).*xp)+6.*vbarp.*(y+(-1).*yp))+(-12).*exp(1).^(a2+3.*logthetax+2.* ...
  logthetay).*(x.^2+(-2).*x.*xp+xp.^2+2.*(y+(-1).*yp).^2)+15.*a1.*exp(1) ...
  .^(4.*logthetax+2.*logthetay).*vbarp.*(y+(-1).*yp)+2.*a1.*exp(1).^( ...
  logthetax+3.*logthetay).*vbarp.*(x+(-1).*xp).^4.*(y+(-1).*yp)+(-12).* ...
  a1.*exp(1).^(3.*logthetax+2.*logthetay).*(x+(-1).*xp).*(vbarp.*(x+(-1).* ...
  xp)+ubarp.*(y+(-1).*yp)).*(y+(-1).*yp)+(-30).*exp(1).^(a2+4.*logthetax+ ...
  logthetay).*(y+(-1).*yp).^2+24.*exp(1).^(a2+3.*logthetax+logthetay).*(x+ ...
  (-1).*xp).^2.*(y+(-1).*yp).^2+36.*exp(1).^(a2+2.*(logthetax+logthetay)) ...
  .*(x+(-1).*xp).^2.*(y+(-1).*yp).^2+3.*a1.*exp(1).^(2.*(logthetax+ ...
  logthetay)).*ubarp.*(x+(-1).*xp).^3.*(y+(-1).*yp).^2+(-4).*exp(1).^(a2+ ...
  logthetax+2.*logthetay).*(x+(-1).*xp).^4.*(y+(-1).*yp).^2+(-5).*a1.*exp( ...
  1).^(4.*logthetax+logthetay).*vbarp.*(y+(-1).*yp).^3+4.*a1.*exp(1).^(3.* ...
  logthetax+logthetay).*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp).^3+5.*exp(1) ...
  .^(a2+4.*logthetax).*(y+(-1).*yp).^4+(-4).*exp(1).^(a2+3.*logthetax).*( ...
  x+(-1).*xp).^2.*(y+(-1).*yp).^4))+(-1).*dt.*exp(1).^a2.*((-6)+(1/2).* ...
  exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2).*((-2).*dt.*exp(1).^(a2+4.* ...
  logthetax+(-2).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+( ...
  -2).*exp(1).^logthetax.*(x+(-1).*xp).*((-2).*exp(1).^(2.*logthetax).*(x+ ...
  (-1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.* ...
  exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(2.* ...
  logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp).^2)) ...
  +(-2).*exp(1).^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*(logthetax+ ...
  logthetay))+dt.*(exp(1).^(a2+2.*logthetax+logthetay)+6.*exp(1).^(a2+ ...
  logthetax+2.*logthetay)+3.*a1.*exp(1).^(logthetax+2.*logthetay).*ubarp.* ...
  (x+(-1).*xp)+(-6).*exp(1).^(a2+2.*logthetay).*(x+(-1).*xp).^2+a1.*exp(1) ...
  .^(2.*logthetax+logthetay).*vbarp.*(y+(-1).*yp)+(-1).*exp(1).^(a2+2.* ...
  logthetax).*(y+(-1).*yp).^2))+((-1).*exp(1).^logthetax+(x+(-1).*xp).^2) ...
  .*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+ ...
  a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+exp(1) ...
  .^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2)+(-2).*dt.*exp(1).^(4.*logthetax+(-3).*logthetay).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2).*(a1.*exp(1).^logthetay.*vbarp+(-2).* ...
  exp(1).^a2.*(y+(-1).*yp)).*(y+(-1).*yp)));


case 3 % logthetay

K=(1/2).*exp(1).^(logsigma+(-6).*logthetax+(-1/2).*exp(1).^((-1).* ...
  logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).* ...
  yp).^2).*((-2).*dt.*exp(1).^(a2+2.*logthetax+(-4).*logthetay).*(exp(1) ...
  .^(2.*(logthetax+logthetay)).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2) ...
  .*(exp(1).^logthetay+(-2).*(y+(-1).*yp).^2)+dt.*(6.*exp(1).^(a2+3.* ...
  logthetax+2.*logthetay)+6.*exp(1).^(a2+2.*logthetax+3.*logthetay)+(-12) ...
  .*exp(1).^(a2+logthetax+3.*logthetay).*(x+(-1).*xp).^2+2.*exp(1).^(a2+ ...
  3.*logthetay).*(x+(-1).*xp).^4+3.*a1.*exp(1).^(2.*logthetax+3.* ...
  logthetay).*(ubarp.*(x+(-1).*xp)+vbarp.*(y+(-1).*yp))+(-1).*a1.*exp(1) ...
  .^(logthetax+3.*logthetay).*(x+(-1).*xp).^2.*(ubarp.*(x+(-1).*xp)+6.* ...
  vbarp.*(y+(-1).*yp))+(-6).*exp(1).^(a2+2.*(logthetax+logthetay)).*(x.^2+ ...
  (-2).*x.*xp+xp.^2+2.*(y+(-1).*yp).^2)+6.*a1.*exp(1).^(3.*logthetax+2.* ...
  logthetay).*vbarp.*(y+(-1).*yp)+a1.*exp(1).^(3.*logthetay).*vbarp.*(x+( ...
  -1).*xp).^4.*(y+(-1).*yp)+(-6).*a1.*exp(1).^(2.*(logthetax+logthetay)).* ...
  (x+(-1).*xp).*(vbarp.*(x+(-1).*xp)+ubarp.*(y+(-1).*yp)).*(y+(-1).*yp)+( ...
  -18).*exp(1).^(a2+3.*logthetax+logthetay).*(y+(-1).*yp).^2+18.*exp(1).^( ...
  a2+2.*logthetax+logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2+24.*exp(1) ...
  .^(a2+logthetax+2.*logthetay).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2+2.*a1.* ...
  exp(1).^(logthetax+2.*logthetay).*ubarp.*(x+(-1).*xp).^3.*(y+(-1).*yp) ...
  .^2+(-4).*exp(1).^(a2+2.*logthetay).*(x+(-1).*xp).^4.*(y+(-1).*yp).^2+( ...
  -3).*a1.*exp(1).^(3.*logthetax+logthetay).*vbarp.*(y+(-1).*yp).^3+3.* ...
  a1.*exp(1).^(2.*logthetax+logthetay).*vbarp.*(x+(-1).*xp).^2.*(y+(-1).* ...
  yp).^3+4.*exp(1).^(a2+3.*logthetax).*(y+(-1).*yp).^4+(-4).*exp(1).^(a2+ ...
  2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^4))+2.*a1.*dt.*exp(1).^( ...
  2.*logthetax+(-3).*logthetay).*(a1.*dt.*exp(1).^(logthetax+logthetay).*( ...
  (-1).*exp(1).^(2.*logthetax+logthetay).*vbar.*vbarp+exp(1).^(logthetax+ ...
  logthetay).*(x+(-1).*xp).*(vbar.*(vbarp.*(x+(-1).*xp)+3.*ubarp.*(y+(-1) ...
  .*yp))+3.*ubar.*vbarp.*(y+(-1).*yp))+(-1).*exp(1).^logthetay.*(ubarp.* ...
  vbar+ubar.*vbarp).*(x+(-1).*xp).^3.*(y+(-1).*yp)+2.*exp(1).^(2.* ...
  logthetax).*vbar.*vbarp.*(y+(-1).*yp).^2+(-2).*exp(1).^logthetax.*vbar.* ...
  vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)+dt.*exp(1).^a2.*(3.*exp(1).^( ...
  2.*(logthetax+logthetay)).*(ubar.*(x+(-1).*xp)+vbar.*(y+(-1).*yp))+(-1) ...
  .*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2.*(ubar.*(x+(-1).*xp) ...
  +6.*vbar.*(y+(-1).*yp))+6.*exp(1).^(3.*logthetax+logthetay).*vbar.*(y+( ...
  -1).*yp)+exp(1).^(2.*logthetay).*vbar.*(x+(-1).*xp).^4.*(y+(-1).*yp)+( ...
  -6).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).*xp).*(vbar.*(x+(-1).*xp) ...
  +ubar.*(y+(-1).*yp)).*(y+(-1).*yp)+2.*exp(1).^(logthetax+logthetay).* ...
  ubar.*(x+(-1).*xp).^3.*(y+(-1).*yp).^2+(-3).*exp(1).^(3.*logthetax).* ...
  vbar.*(y+(-1).*yp).^3+3.*exp(1).^(2.*logthetax).*vbar.*(x+(-1).*xp).^2.* ...
  (y+(-1).*yp).^3)+exp(1).^(2.*(logthetax+logthetay)).*vbar.*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2).*(y+(-1).*yp))+(-2).*dt.*exp(1).^(4.* ...
  logthetax+(-2).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*( ...
  exp(1).^(a2+logthetay)+a1.*exp(1).^logthetay.*vbarp.*(y+(-1).*yp)+(-2).* ...
  exp(1).^a2.*(y+(-1).*yp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay) ...
  .*(ubar.*(exp(1).^logthetax.*((-2).*exp(1).^(2.*logthetax).*(x+(-1).*xp) ...
  +a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+(-2).* ...
  exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^(2.*logthetax+ ...
  logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp).^2))+( ...
  -1).*(x+(-1).*xp).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+ ...
  (-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)))+exp( ...
  1).^(logthetax+(-2).*logthetay).*vbar.*(a1.*dt.*exp(1).^(2.*logthetax+ ...
  logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+(-2).*dt.* ...
  exp(1).^(a2+2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*( ...
  y+(-1).*yp)+(-1).*exp(1).^logthetay.*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp))).*(y+(-1).*yp).^2+exp(1) ...
  .^(2.*logthetax+(-1).*logthetay).*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp).^2+(-1).*dt.*exp(1).^(a2+( ...
  -1).*logthetay).*((-2).*dt.*exp(1).^(a2+4.*logthetax+(-2).*logthetay).*( ...
  exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+(-2).*exp(1).^logthetax.*(x+( ...
  -1).*xp).*((-2).*exp(1).^(2.*logthetax).*(x+(-1).*xp)+a1.*dt.*exp(1).^( ...
  logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp+( ...
  -3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^2+(-2).*exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+2.*dt.*exp(1).^(a2+(-2).*logthetay).* ...
  (x+(-1).*xp).*((-1).*exp(1).^(2.*logthetax+logthetay)+(-6).*exp(1).^( ...
  logthetax+2.*logthetay)+2.*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+exp( ...
  1).^(2.*logthetax).*(y+(-1).*yp).^2))+(-2).*exp(1).^(2.*logthetax+(-2).* ...
  logthetay).*(exp(1).^(2.*(logthetax+logthetay))+dt.*(exp(1).^(a2+2.* ...
  logthetax+logthetay)+6.*exp(1).^(a2+logthetax+2.*logthetay)+3.*a1.*exp( ...
  1).^(logthetax+2.*logthetay).*ubarp.*(x+(-1).*xp)+(-6).*exp(1).^(a2+2.* ...
  logthetay).*(x+(-1).*xp).^2+a1.*exp(1).^(2.*logthetax+logthetay).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^(a2+2.*logthetax).*(y+(-1).*yp).^2))+( ...
  (-1).*exp(1).^logthetax+(x+(-1).*xp).^2).*(exp(1).^(2.*logthetax).*(exp( ...
  1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2))+exp(1).^(2.*logthetax+(-2).*logthetay).*( ...
  exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.* ...
  dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)).*((-1) ...
  .*exp(1).^logthetay+(y+(-1).*yp).^2)+(-2).*dt.*exp(1).^(4.*logthetax+( ...
  -3).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).*(a1.*exp(1) ...
  .^logthetay.*vbarp+(-2).*exp(1).^a2.*(y+(-1).*yp)).*(y+(-1).*yp)).*(y+( ...
  -1).*yp).^2);


case 4 % a1

K=dt.*exp(1).^(logsigma+(-6).*logthetax+(-1/2).*exp(1).^((-1).*logthetax) ...
  .*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*( ...
  exp(1).^logthetax.*(ubar.*(exp(1).^logthetax.*((-2).*exp(1).^(2.* ...
  logthetax).*(x+(-1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*( ...
  3.*exp(1).^(logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp))+2.*dt.*exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^( ...
  2.*logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1) ...
  .^(2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+(-1).*(x+(-1).*xp).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+( ...
  -1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.* ...
  exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+( ...
  -1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+ ...
  dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay)) ...
  +exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay) ...
  .*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax) ...
  .*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp) ...
  .^2)))+exp(1).^(logthetax+(-2).*logthetay).*vbar.*(a1.*dt.*exp(1).^(2.* ...
  logthetax+logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+( ...
  -2).*dt.*exp(1).^(a2+2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).* ...
  xp).^2).*(y+(-1).*yp)+(-1).*exp(1).^logthetay.*(exp(1).^(2.*logthetax).* ...
  (exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+( ...
  -1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+ ...
  (-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp)))+a1.*dt.*exp(1).^(2.* ...
  logthetax+(-2).*logthetay).*(exp(1).^logthetay.*ubar.*(3.*exp(1).^(2.* ...
  logthetax+logthetay).*ubarp+(-6).*exp(1).^(logthetax+logthetay).*ubarp.* ...
  (x+(-1).*xp).^2+exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^4+(-3).*exp(1) ...
  .^(2.*logthetax).*vbarp.*(x+(-1).*xp).*(y+(-1).*yp)+exp(1).^logthetax.* ...
  vbarp.*(x+(-1).*xp).^3.*(y+(-1).*yp))+exp(1).^logthetax.*vbar.*(exp(1) ...
  .^(logthetax+logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp) ...
  .^2)+(-1).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).* ...
  exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp)).*(y+(-1).*yp)))+(-1).*dt.*exp(1).^(a2+logthetax+(-3).* ...
  logthetay).*((-2).*exp(1).^(2.*(logthetax+logthetay)).*(3.*exp(1) ...
  .^logthetay.*ubarp.*(x+(-1).*xp)+exp(1).^logthetax.*vbarp.*(y+(-1).*yp)) ...
  +(-2).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp) ...
  .^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).*yp))+exp(1) ...
  .^(2.*logthetay).*((-1).*exp(1).^logthetax+(x+(-1).*xp).^2).*(3.*exp(1) ...
  .^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+exp(1).^(2.* ...
  logthetax).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp)).*((-1).*exp(1).^logthetay+(y+(-1).*yp).^2)+(-2).*exp(1).^(3.* ...
  logthetax+logthetay).*vbarp.*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2).* ...
  (y+(-1).*yp))+exp(1).^(3.*logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp)));


case 5 % a2

K=dt.*exp(1).^(logsigma+(-6).*logthetax+(-1/2).*exp(1).^((-1).*logthetax) ...
  .*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*( ...
  a1.*dt.*exp(1).^(a2+logthetax+(-2).*logthetay).*(ubar.*(x+(-1).*xp).*(( ...
  -15).*exp(1).^(2.*(logthetax+logthetay))+(-3).*exp(1).^(3.*logthetax+ ...
  logthetay)+exp(1).^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+10.*exp(1) ...
  .^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetay) ...
  .*(x+(-1).*xp).^4+3.*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+(-1).*exp( ...
  1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)+exp(1) ...
  .^logthetax.*vbar.*((-2).*exp(1).^(2.*logthetax).*(exp(1).^logthetax+( ...
  -1).*(x+(-1).*xp).^2)+(-1).*exp(1).^((-1).*logthetay).*(3.*exp(1).^(2.*( ...
  logthetax+logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^( ...
  2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*(y+(-1).*yp))+exp(1).^a2.*(2.*dt.*exp(1) ...
  .^(a2+4.*logthetax+(-2).*logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).* ...
  xp).^2)+2.*exp(1).^logthetax.*(x+(-1).*xp).*((-2).*exp(1).^(2.* ...
  logthetax).*(x+(-1).*xp)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*( ...
  3.*exp(1).^(logthetax+logthetay).*ubarp+(-3).*exp(1).^logthetay.*ubarp.* ...
  (x+(-1).*xp).^2+(-2).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).*(y+(-1).* ...
  yp))+2.*dt.*exp(1).^(a2+(-2).*logthetay).*(x+(-1).*xp).*((-1).*exp(1).^( ...
  2.*logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.*logthetay)+2.*exp(1) ...
  .^(2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetax).*(y+(-1).*yp) ...
  .^2))+2.*exp(1).^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*( ...
  logthetax+logthetay))+dt.*(exp(1).^(a2+2.*logthetax+logthetay)+6.*exp(1) ...
  .^(a2+logthetax+2.*logthetay)+3.*a1.*exp(1).^(logthetax+2.*logthetay).* ...
  ubarp.*(x+(-1).*xp)+(-6).*exp(1).^(a2+2.*logthetay).*(x+(-1).*xp).^2+ ...
  a1.*exp(1).^(2.*logthetax+logthetay).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^(a2+2.*logthetax).*(y+(-1).*yp).^2))+(-1).*((-1).*exp(1).^logthetax+( ...
  x+(-1).*xp).^2).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+( ...
  -1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^( ...
  logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+(-1).* ...
  exp(1).^(2.*logthetax+(-2).*logthetay).*(exp(1).^(2.*logthetax).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+ ...
  logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.* ...
  logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.* ...
  logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1) ...
  .*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+( ...
  -1).*xp).^2.*(y+(-1).*yp).^2)).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2)+2.*dt.*exp(1).^(4.*logthetax+(-3).*logthetay).*(exp(1).^logthetax+( ...
  -1).*(x+(-1).*xp).^2).*(a1.*exp(1).^logthetay.*vbarp+(-2).*exp(1).^a2.*( ...
  y+(-1).*yp)).*(y+(-1).*yp))+(-1).*dt.*exp(1).^(a2+(-4).*logthetay).*(( ...
  -2).*exp(1).^(a2+4.*logthetax+2.*logthetay).*(exp(1).^logthetax+(-1).*( ...
  x+(-1).*xp).^2)+(-2).*exp(1).^(a2+2.*(logthetax+logthetay)).*(exp(1).^( ...
  2.*logthetax+logthetay)+6.*exp(1).^(logthetax+2.*logthetay)+(-6).*exp(1) ...
  .^(2.*logthetay).*(x+(-1).*xp).^2+(-1).*exp(1).^(2.*logthetax).*(y+(-1) ...
  .*yp).^2)+(-4).*exp(1).^(a2+logthetax+2.*logthetay).*(x+(-1).*xp).^2.*(( ...
  -1).*exp(1).^(2.*logthetax+logthetay)+(-6).*exp(1).^(logthetax+2.* ...
  logthetay)+2.*exp(1).^(2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.* ...
  logthetax).*(y+(-1).*yp).^2)+exp(1).^(a2+2.*logthetay).*((-1).*exp(1) ...
  .^logthetax+(x+(-1).*xp).^2).*(3.*exp(1).^(2.*(logthetax+logthetay))+ ...
  exp(1).^(3.*logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay) ...
  .*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp) ...
  .^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax) ...
  .*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp) ...
  .^2)+exp(1).^(a2+2.*logthetax).*((-1).*exp(1).^logthetay+(y+(-1).*yp) ...
  .^2).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.*logthetax+ ...
  logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6) ...
  .*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.* ...
  logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).*yp) ...
  .^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)+4.*exp(1) ...
  .^(a2+4.*logthetax+logthetay).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2) ...
  .*(y+(-1).*yp).^2)+exp(1).^(a2+2.*logthetax+(-2).*logthetay).*(3.*exp(1) ...
  .^(2.*(logthetax+logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1).*exp( ...
  1).^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^(logthetax+ ...
  2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1).*xp).^4+( ...
  -1).*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.*logthetax).*(x+ ...
  (-1).*xp).^2.*(y+(-1).*yp).^2));


case 6 % logsigmap

K=dt.^2.*exp(1).^(logsigmap+(-2).*logthetayp+(-1/2).*exp(1).^((-1).* ...
  logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetayp).*(y+(-1) ...
  .*yp).^2).*(exp(1).^logthetayp+(-1).*(y+(-1).*yp).^2);


case 7 % logthetaxp

K=(1/2).*dt.^2.*exp(1).^(logsigmap+(-1).*logthetaxp+(-2).*logthetayp+( ...
  -1/2).*exp(1).^((-1).*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1) ...
  .*logthetayp).*(y+(-1).*yp).^2).*(x+(-1).*xp).^2.*(exp(1).^logthetayp+( ...
  -1).*(y+(-1).*yp).^2);


case 8 % logthetayp

K=(-1/2).*dt.^2.*exp(1).^(logsigmap+(-3).*logthetayp+(-1/2).*exp(1).^((-1) ...
  .*logthetaxp).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetayp).*(y+( ...
  -1).*yp).^2).*(2.*exp(1).^(2.*logthetayp)+(-5).*exp(1).^logthetayp.*(y+( ...
  -1).*yp).^2+(y+(-1).*yp).^4);


otherwise
        
        K = zeros(n_x, n_xp);
end

end
