function [K] = ku0u0(x, xp, hyp, ubar, ubarp, dt, i)

logsigma = hyp(1);
logtheta = hyp(2);

a1 = hyp(3);
a2 = hyp(4);

n_x = size(x,1);
n_xp = size(xp,1);

x = repmat(x,1,n_xp);
xp = repmat(xp',n_x,1);

ubar = repmat(ubar,1,n_xp);
ubarp = repmat(ubarp',n_x,1);

switch i


case 0

K=exp(1).^(logsigma+(-6).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(4.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.* ...
  exp(1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1) ...
  .*xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+(-1).*a1.*a2.* ...
  dt.^2.*exp(1).^(2.*logtheta).*(ubar+ubarp).*(3.*exp(1).^(2.*logtheta)+( ...
  -6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4)+a2.^2.*dt.^2.*( ...
  15.*exp(1).^(3.*logtheta)+(-45).*exp(1).^(2.*logtheta).*(x+(-1).*xp).^2+ ...
  15.*exp(1).^logtheta.*(x+(-1).*xp).^4+(-1).*(x+(-1).*xp).^6));


case 1 % logsigma

K=exp(1).^(logsigma+(-6).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(4.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.* ...
  exp(1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1) ...
  .*xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+(-1).*a1.*a2.* ...
  dt.^2.*exp(1).^(2.*logtheta).*(ubar+ubarp).*(3.*exp(1).^(2.*logtheta)+( ...
  -6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4)+a2.^2.*dt.^2.*( ...
  15.*exp(1).^(3.*logtheta)+(-45).*exp(1).^(2.*logtheta).*(x+(-1).*xp).^2+ ...
  15.*exp(1).^logtheta.*(x+(-1).*xp).^4+(-1).*(x+(-1).*xp).^6));


case 2 % logtheta

K=exp(1).^(logsigma+(-6).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(5.*logtheta).*(2.*exp(1).^logtheta+a1.*dt.*(a1.* ...
  dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1).*xp)))+(-6).*a1.*a2.* ...
  dt.^2.*exp(1).^(3.*logtheta).*(ubar+ubarp).*(exp(1).^logtheta+(-1).*(x+( ...
  -1).*xp).^2)+(exp(1).^(4.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.*exp( ...
  1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1).* ...
  xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+(-1).*a1.*a2.* ...
  dt.^2.*exp(1).^(2.*logtheta).*(ubar+ubarp).*(3.*exp(1).^(2.*logtheta)+( ...
  -6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4)+a2.^2.*dt.^2.*( ...
  15.*exp(1).^(3.*logtheta)+(-45).*exp(1).^(2.*logtheta).*(x+(-1).*xp).^2+ ...
  15.*exp(1).^logtheta.*(x+(-1).*xp).^4+(-1).*(x+(-1).*xp).^6)).*((-6)+( ...
  1/2).*exp(1).^((-1).*logtheta).*(x+(-1).*xp).^2)+4.*exp(1).^(4.* ...
  logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.*exp(1).^logtheta.*(a1.*dt.* ...
  ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1).*xp))+(-1).*a1.^2.*dt.^2.* ...
  ubar.*ubarp.*(x+(-1).*xp).^2)+15.*a2.^2.*dt.^2.*exp(1).^logtheta.*(3.* ...
  exp(1).^(2.*logtheta)+(-6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).* ...
  xp).^4)+(-2).*a1.*a2.*dt.^2.*exp(1).^(2.*logtheta).*(ubar+ubarp).*(3.* ...
  exp(1).^(2.*logtheta)+(-6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).* ...
  xp).^4));


case 3 % a1

K=dt.*exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*( ...
  x+(-1).*xp).^2).*(exp(1).^(2.*logtheta).*(2.*a1.*dt.*ubar.*ubarp.*(exp( ...
  1).^logtheta+(-1).*(x+(-1).*xp).^2)+(-1).*exp(1).^logtheta.*(ubar+(-1).* ...
  ubarp).*(x+(-1).*xp))+(-1).*a2.*dt.*(ubar+ubarp).*(3.*exp(1).^(2.* ...
  logtheta)+(-6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4));


case 4 % a2

K=dt.^2.*exp(1).^(logsigma+(-6).*logtheta+(-1/2).*exp(1).^((-1).*logtheta) ...
  .*(x+(-1).*xp).^2).*((-1).*a1.*exp(1).^(2.*logtheta).*(ubar+ubarp).*(3.* ...
  exp(1).^(2.*logtheta)+(-6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).* ...
  xp).^4)+2.*a2.*(15.*exp(1).^(3.*logtheta)+(-45).*exp(1).^(2.*logtheta).* ...
  (x+(-1).*xp).^2+15.*exp(1).^logtheta.*(x+(-1).*xp).^4+(-1).*(x+(-1).*xp) ...
  .^6));


otherwise
        
        K = zeros(n_x, n_xp);
end

if K == 0

    K = zeros(n_x, n_xp);

end

end
