function [K] = kv1v0(x, y, xp, yp, hyp, ubarp, vbarp, dt, i)

logsigma = hyp(1);
logthetax = hyp(2);
logthetay = hyp(3);

a1 = hyp(4);
a2 = hyp(5);

n_x = size(x,1);
n_y = size(y,1);
n_xp = size(xp,1);
n_yp = size(yp,1);

x = repmat(x,1,n_xp);
y = repmat(y,1,n_yp);
xp = repmat(xp',n_x,1);
yp = repmat(yp',n_y,1);

ubarp = repmat(ubarp',n_x,1);
vbarp = repmat(vbarp',n_y,1);

switch i


case 0

K=exp(1).^(logsigma+(-4).*logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+ ...
  (-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(exp( ...
  1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.* ...
  exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).* ...
  ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp( ...
  1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.* ...
  (x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.* ...
  exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1) ...
  .*exp(1).^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1) ...
  .*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.* ...
  logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2));


case 1 % logsigma

K=exp(1).^(logsigma+(-4).*logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+ ...
  (-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(exp( ...
  1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+a1.*dt.* ...
  exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+logthetay).* ...
  ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp( ...
  1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.* ...
  (x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2).*logthetay).*(3.* ...
  exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.*logthetax+logthetay)+(-1) ...
  .*exp(1).^(2.*logthetax+logthetay).*(x+(-1).*xp).^2+(-6).*exp(1).^( ...
  logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^(2.*logthetay).*(x+(-1) ...
  .*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).*yp).^2+exp(1).^(2.* ...
  logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2));


case 2 % logthetax

K=exp(1).^(logsigma+(-4).*logthetax+(-1/2).*exp(1).^((-1).*logthetax).*(x+ ...
  (-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).*yp).^2).*(exp( ...
  1).^(3.*logthetax)+2.*exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*( ...
  x+(-1).*xp).^2)+((-4)+(1/2).*exp(1).^((-1).*logthetax).*(x+(-1).*xp).^2) ...
  .*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1).*(x+(-1).*xp).^2)+ ...
  a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp(1).^(logthetax+ ...
  logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.*ubarp.*(x+(-1) ...
  .*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1).*exp(1) ...
  .^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^(a2+(-2) ...
  .*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2))+a1.* ...
  dt.*exp(1).^(2.*logthetax+(-1).*logthetay).*(3.*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp)+2.*exp(1).^logthetax.*vbarp.*(y+(-1).*yp)+(-1).* ...
  vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+a1.*dt.*exp(1).^(logthetax+(-1).* ...
  logthetay).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1) ...
  .*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp))+dt.*exp(1).^(a2+logthetax+(-2).*logthetay).*(3.*exp(1).^(2.* ...
  logthetax+logthetay)+6.*exp(1).^(logthetax+2.*logthetay)+(-6).*exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^2+(-2).*exp(1).^(logthetax+logthetay).*(x+( ...
  -1).*xp).^2+(-3).*exp(1).^(2.*logthetax).*(y+(-1).*yp).^2+2.*exp(1) ...
  .^logthetax.*(x+(-1).*xp).^2.*(y+(-1).*yp).^2));


case 3 % logthetay

K=(1/2).*exp(1).^(logsigma+(-4).*logthetax+(-1/2).*exp(1).^((-1).* ...
  logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+(-1).* ...
  yp).^2).*((-2).*dt.*exp(1).^(2.*logthetax+(-2).*logthetay).*(exp(1) ...
  .^logthetax+(-1).*(x+(-1).*xp).^2).*(exp(1).^(a2+logthetay)+a1.*exp(1) ...
  .^logthetay.*vbarp.*(y+(-1).*yp)+(-2).*exp(1).^a2.*(y+(-1).*yp).^2)+exp( ...
  1).^((-1).*logthetay).*(exp(1).^(2.*logthetax).*(exp(1).^logthetax+(-1) ...
  .*(x+(-1).*xp).^2)+a1.*dt.*exp(1).^(logthetax+(-1).*logthetay).*(3.*exp( ...
  1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+(-1).*exp(1).^logthetay.* ...
  ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).*vbarp.*(y+(-1).*yp)+(-1) ...
  .*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+(-1).*yp))+dt.*exp(1).^( ...
  a2+(-2).*logthetay).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2)).*(y+( ...
  -1).*yp).^2);


case 4 % a1

K=dt.*exp(1).^(logsigma+(-3).*logthetax+(-1).*logthetay+(-1/2).*exp(1).^(( ...
  -1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).*(y+( ...
  -1).*yp).^2).*(3.*exp(1).^(logthetax+logthetay).*ubarp.*(x+(-1).*xp)+( ...
  -1).*exp(1).^logthetay.*ubarp.*(x+(-1).*xp).^3+exp(1).^(2.*logthetax).* ...
  vbarp.*(y+(-1).*yp)+(-1).*exp(1).^logthetax.*vbarp.*(x+(-1).*xp).^2.*(y+ ...
  (-1).*yp));


case 5 % a2

K=dt.*exp(1).^(a2+logsigma+(-4).*logthetax+(-2).*logthetay+(-1/2).*exp(1) ...
  .^((-1).*logthetax).*(x+(-1).*xp).^2+(-1/2).*exp(1).^((-1).*logthetay).* ...
  (y+(-1).*yp).^2).*(3.*exp(1).^(2.*(logthetax+logthetay))+exp(1).^(3.* ...
  logthetax+logthetay)+(-1).*exp(1).^(2.*logthetax+logthetay).*(x+(-1).* ...
  xp).^2+(-6).*exp(1).^(logthetax+2.*logthetay).*(x+(-1).*xp).^2+exp(1).^( ...
  2.*logthetay).*(x+(-1).*xp).^4+(-1).*exp(1).^(3.*logthetax).*(y+(-1).* ...
  yp).^2+exp(1).^(2.*logthetax).*(x+(-1).*xp).^2.*(y+(-1).*yp).^2);


otherwise
        
        K = zeros(n_x, n_xp);
end

end
