function [K] = ku0u0(x, xp, hyp, ubar, ubarp, dt, i)

logsigma = hyp(1);
logtheta = hyp(2);

a1 = hyp(3);
a2 = hyp(4);

n_x = size(x,1);
n_xp = size(xp,1);

x = repmat(x,1,n_xp);
xp = repmat(xp',n_x,1);

ubar = repmat(ubar,1,n_xp);
ubarp = repmat(ubarp',n_x,1);

switch i


case 0

K=exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(2.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.* ...
  exp(1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1) ...
  .*xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+a2.*dt.*exp(1) ...
  .^logtheta.*(2.*exp(1).^(2.*logtheta)+(-1).*exp(1).^logtheta.*(3.*a1.* ...
  dt.*(ubar+(-1).*ubarp)+2.*(x+(-1).*xp)).*(x+(-1).*xp)+a1.*dt.*(ubar+(-1) ...
  .*ubarp).*(x+(-1).*xp).^3)+a2.^2.*dt.^2.*(3.*exp(1).^(2.*logtheta)+(-6) ...
  .*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4));


case 1 % logsigma

K=exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(2.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.* ...
  exp(1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1) ...
  .*xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+a2.*dt.*exp(1) ...
  .^logtheta.*(2.*exp(1).^(2.*logtheta)+(-1).*exp(1).^logtheta.*(3.*a1.* ...
  dt.*(ubar+(-1).*ubarp)+2.*(x+(-1).*xp)).*(x+(-1).*xp)+a1.*dt.*(ubar+(-1) ...
  .*ubarp).*(x+(-1).*xp).^3)+a2.^2.*dt.^2.*(3.*exp(1).^(2.*logtheta)+(-6) ...
  .*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4));


case 2 % logtheta

K=exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2).*(exp(1).^(3.*logtheta).*(2.*exp(1).^logtheta+a1.*dt.*(a1.* ...
  dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1).*xp)))+a2.*dt.*exp(1) ...
  .^(2.*logtheta).*(4.*exp(1).^logtheta+(-1).*(3.*a1.*dt.*(ubar+(-1).* ...
  ubarp)+2.*(x+(-1).*xp)).*(x+(-1).*xp))+6.*a2.^2.*dt.^2.*exp(1) ...
  .^logtheta.*(exp(1).^logtheta+(-1).*(x+(-1).*xp).^2)+(exp(1).^(2.* ...
  logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.*exp(1).^logtheta.*(a1.*dt.* ...
  ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1).*xp))+(-1).*a1.^2.*dt.^2.* ...
  ubar.*ubarp.*(x+(-1).*xp).^2)+a2.*dt.*exp(1).^logtheta.*(2.*exp(1).^(2.* ...
  logtheta)+(-1).*exp(1).^logtheta.*(3.*a1.*dt.*(ubar+(-1).*ubarp)+2.*(x+( ...
  -1).*xp)).*(x+(-1).*xp)+a1.*dt.*(ubar+(-1).*ubarp).*(x+(-1).*xp).^3)+ ...
  a2.^2.*dt.^2.*(3.*exp(1).^(2.*logtheta)+(-6).*exp(1).^logtheta.*(x+(-1) ...
  .*xp).^2+(x+(-1).*xp).^4)).*((-4)+(1/2).*exp(1).^((-1).*logtheta).*(x+( ...
  -1).*xp).^2)+2.*exp(1).^(2.*logtheta).*(exp(1).^(2.*logtheta)+a1.*dt.* ...
  exp(1).^logtheta.*(a1.*dt.*ubar.*ubarp+(-1).*(ubar+(-1).*ubarp).*(x+(-1) ...
  .*xp))+(-1).*a1.^2.*dt.^2.*ubar.*ubarp.*(x+(-1).*xp).^2)+a2.*dt.*exp(1) ...
  .^logtheta.*(2.*exp(1).^(2.*logtheta)+(-1).*exp(1).^logtheta.*(3.*a1.* ...
  dt.*(ubar+(-1).*ubarp)+2.*(x+(-1).*xp)).*(x+(-1).*xp)+a1.*dt.*(ubar+(-1) ...
  .*ubarp).*(x+(-1).*xp).^3));


case 3 % a1

K=dt.*exp(1).^(logsigma+(-3).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*( ...
  x+(-1).*xp).^2).*(exp(1).^logtheta.*(2.*a1.*dt.*ubar.*ubarp.*(exp(1) ...
  .^logtheta+(-1).*(x+(-1).*xp).^2)+(-1).*exp(1).^logtheta.*(ubar+(-1).* ...
  ubarp).*(x+(-1).*xp))+a2.*dt.*(ubar+(-1).*ubarp).*((-3).*exp(1) ...
  .^logtheta+(x+(-1).*xp).^2).*(x+(-1).*xp));


case 4 % a2

K=dt.*exp(1).^(logsigma+(-4).*logtheta+(-1/2).*exp(1).^((-1).*logtheta).*( ...
  x+(-1).*xp).^2).*(exp(1).^logtheta.*(2.*exp(1).^(2.*logtheta)+(-1).*exp( ...
  1).^logtheta.*(3.*a1.*dt.*(ubar+(-1).*ubarp)+2.*(x+(-1).*xp)).*(x+(-1).* ...
  xp)+a1.*dt.*(ubar+(-1).*ubarp).*(x+(-1).*xp).^3)+2.*a2.*dt.*(3.*exp(1) ...
  .^(2.*logtheta)+(-6).*exp(1).^logtheta.*(x+(-1).*xp).^2+(x+(-1).*xp).^4) ...
  );


otherwise
        
        K = zeros(n_x, n_xp);
end

if K == 0

    K = zeros(n_x, n_xp);

end

end
